language: python
python:
  - "2.7"
# command to install dependencies

before_install:
  - pip install clustershell
  - pip install codecov

install:
  - cd datastore
  - pip install .
  - pip install -r requirements.txt
  - cd ../actsys
  - pip install .
  - pip install -r requirements.txt
  - cd ..
# command to run tests
#  The first runs pylint, reads the code raiting and errors if the rating is below 8.
#  The second runs the tests.
script:
  - cd actsys
  - pylint --ignore-patterns=test* control | tee /dev/tty | gawk 'match($0, /[0-9]\.[0-9]*\//, a) {exit a[1]}' || [[ $? == 0 || $? -ge 8 ]]
  - python -m pytest . --cov=control --cov-report term-missing --cov-report xml
  - cd ../datastore
  - pylint --ignore-patterns=test* datastore | tee /dev/tty | gawk 'match($0, /[0-9]\.[0-9]*\//, a) {exit a[1]}' || [[ $? == 0 || $? -ge 8 ]]
  - python -m pytest . --cov=datastore --cov-report term-missing --cov-report xml
after_success:
  - codecov
