site_name: Actsys
repo_url: https://github.com/intel-ctrlsys/actsys/
theme: readthedocs
pages:
    - 'Overview': 'index.md'
    - 'User Guide':
        - 'Quick Start': 'quick-start.md'
        - 'Installation Instructions': 'installation-instructions.md'
        - 'Configuration File': 'configuration-file.md'
        - 'Command Interface': 'command-interface.md'
        - 'Power Commands': 'power-commands.md'
        - 'Resource Commands': 'resource-commands.md'
        - 'Service Commands': 'service-commands.md'
        - 'Bios Commands': 'bios-commands.md'
        - 'Provision Commands': 'provision-commands.md'
        - 'OOB Sensor Commands': 'oob-sensor-commands.md'
        - 'Rest API Commands': 'rest-api-commands.md'
        - 'Diagnostics Commands': 'diagnostics-commands.md'
        - 'Command Timeout': 'command-timeout.md'
        - 'Journal Log File': 'journal-log-file.md'
    - 'Developer Guide':
        - 'Overview': 'developer-overview.md'
        - 'Power Control Plugins': 'power-control-plugins.md'
        - 'Resource Control Plugins': 'resource-control-plugins.md'
        - 'Configuration Manager': 'configuration-manager.md'
        - 'Journal Logger': 'journal-logger.md'
        - 'Provisioner Plugins': 'provisioner-plugins.md'
        - 'OOB Sensor Plugins': 'oob-sensor-plugins.md'
        - 'Diagnostics Plugins': 'diagnostics-plugins.md'
    - 'License': 'license.md'
